UIPCIR-72: Cover `PrimaryToggleButton` component with unit tests
folio-org/ui-plugin-create-inventory-records pull request #164
Opened 2024-03-14 15:25 UTC by OleksandrHladchenko1

## Links
[UIPCIR-72](https://folio-org.atlassian.net/browse/UIPCIR-72)

## Screenshots
![image](https://github.com/folio-org/ui-plugin-create-inventory-records/assets/85172747/66849c10-0cd6-4a16-8073-b2218a2f7408)

2024-03-18 11:51 UTC, Dmytro-Melnyshyn approved these changes

2024-03-18 16:40 UTC, BogdanDenis requested changes

2024-03-18 16:40 UTC, BogdanDenis commented on src/components/PrimaryToggleButton/PrimaryToggleButton.test.js
> +describe('PrimaryToggleButton component', () => {
Please clear mocks before each test

2024-03-18 20:37 UTC, zburke approved these changes

2024-03-19 16:19 UTC, BogdanDenis approved these changes

2024-03-19 17:30 UTC, merged