UIPCIR-21: Update circulation interface dependency to support v11
folio-org/ui-plugin-create-inventory-records pull request #70
Opened 2021-05-20 12:21 UTC by Dmitriy-Litvinenko

## Purpose
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.

**Do not merge. We have several associated pull request and we need merge them at the same time.**

**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module

## Refs
https://issues.folio.org/browse/UIPCIR-21

2021-05-20 12:23 UTC, Dmitriy-Litvinenko commented
@zburke @mkuklis Could you please review? Do you have permission for merge in current repository?

2021-05-20 12:43 UTC, NikitaSedyx commented on package.json
> +      "circulation": "9.0 10.0 11.0"
I believe 9.0 can be removed as well

2021-05-20 12:57 UTC, Dmitriy-Litvinenko commented on package.json
> +      "circulation": "9.0 10.0 11.0"
Fixed

2021-05-20 13:18 UTC, zburke requested changes
Technically, removing support for 9.0 is a breaking change for this repo, so if you're going to do that you need to bump the major version. This was the path we took with the 9 -> 10 interface upgrade since, like this one, the only breaking change then was dropping another override-related endpoint that this module did not use. That said, keeping a narrow selection of interfaces helps keep the support surface small, and there is value in that. 

Personally, I would leave 9.0 in there so we don't create the burden of upgrading this plugin's version in all the apps that use it. It's trivial work, but still work. Your call though, and I'll support either decision.

2021-05-20 14:11 UTC, Dmitriy-Litvinenko commented
@zburke @NikitaSedyx Could you please re-review?

2021-05-20 14:31 UTC, zburke approved these changes

2021-05-21 06:17 UTC, NikitaSedyx approved these changes

2021-05-21 13:07 UTC, merged